# Generated by Django 2.2 on 2020-09-01 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='upper_category',
        ),
        migrations.AddField(
            model_name='category',
            name='sub_category_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.MainCategory'),
        ),
    ]
