# Generated by Django 2.2 on 2020-09-03 16:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20200901_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_category_of',
            field=models.ForeignKey(default=datetime.datetime(2020, 9, 3, 16, 41, 12, 217279, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='categories.MainCategory'),
            preserve_default=False,
        ),
    ]
