# Generated by Django 2.2 on 2020-09-01 22:04

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='post',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
