# Generated by Django 2.2 on 2020-09-03 16:39

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='post',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
