# Generated by Django 2.2 on 2020-09-13 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200913_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='label',
            field=models.CharField(blank=True, choices=[('برگزیده', 'برگزیده'), ('تخفیف', 'تخفیف'), ('پرفروش', 'پرفروش'), ('تولید داخل', 'تولید داخل'), ('شب یلدا', 'شب یلدا'), ('پیشنهاد ویژه', 'پیشنهاد ویژه')], max_length=32, null=True),
        ),
    ]
